### ISSUE TITLE
All Screens - Overall: Typography

### ISSUE THREAD

**Issue by holly-johnson** [gdma-web/GDMA-2662-Probono-Website#32]
- Additional line-height (I went all the way to 1.9) would really give your site much more breath and feel lighter and more welcoming.
- The weight of the button typography doesn't balance well with the thin line around. Even bringing it down to 600 feels much more balanced. 
- There isn't a ton of contrast between the h3's and the body copy. The uppercase also causes a lot of tension for me when reading. When I removed the uppercasing and the override media query (so camel case and 1.25rem) it was already feeling better.

**Comment by TayHays** [comment]
Confirmed
