### ISSUE TITLE
All Screens - Facebook: Making Text Link

### ISSUE THREAD

**Issue by holly-johnson** [gdma-web/GDMA-2662-Probono-Website#34]
I attempted to click on "Find us on Facebook" I would also make the text a link. Users will intuitively try and click a CTA "Find Us on Facebook!" and if it's not clickable will be a bit frustrating.

**Comment by holly-johnson** [comment]
Same with Twitter. I would also be consistent - "Twitter" (Icon) OR (Icon) "Follow Us on Facebook"

**Comment by TayHays** [comment]
Confirmed
