### ISSUE TITLE
All Screens - Provider Sections: Typography

### ISSUE THREAD

**Issue by holly-johnson** [gdma-web/GDMA-2662-Probono-Website#35]
<img width="882" alt="screen shot 2018-12-07 at 3 08 18 pm" src="https://user-images.githubusercontent.com/15253544/49672990-95014f80-fa32-11e8-857c-6f06a83d4789.png">

The sections of typography are too scattered. Chunk them more to keep like with like. See the attached. (you'll notice I also added more line height which is making it look different).

Space this section how you would with a business card. Less equal spacing - more groupings.

**Comment by anita-epp** [comment]
Wait for Push. Added less space between name and title, and between Office Hours and Hours. (MPP and IPP's)

**Comment by TayHays** [comment]
Fixed on MPP and Confirmed
