### ISSUE TITLE
All Screens - Contact: Footer

### ISSUE THREAD

**Issue by holly-johnson** [gdma-web/GDMA-2662-Probono-Website#38]
While I get you want to provide more importance to the map on the contact page, it may be confusing to the user that the footer isn't the same footer as the other pages. It also doesn't feel like a footer so I continued to scroll to see if there was more. I would honestly stick with the normal footer on this page. My previous issue about making the footer taller may help this page feel a bit more prominent.

**Comment by anita-epp** [comment]
Wait till push

**Comment by TayHays** [comment]
Confirmed
